export enum LoadPath {
  DAI_TU = 'daitu',
  DAI_TU_CHI_DINH = 'daituchidinh',
  DANH_TU = 'danhtu',
  DANH_TU_CHI_DVDL = 'danhtuchidonvidoluong',
  DANH_TU_LOAI_THE = 'danhtuloaithe',
  DINH_TU_CHI_SO_LUONG = 'dinhtuchisoluong',
  DONG_TU = 'dongtu',
  PHO_TU_DUNG_SAU = 'photudungsau',
  PHO_TU_DUNG_TRUOC = 'photudungtruoc',
  QUAN_HE_TU = 'quanhetu',
  SO_TU_CHI_SO_LUONG = 'sotuchisoluong',
  THAN_TU = 'thantu',
  TINH_THAI_TU = 'tinhthaitu',
  TINH_THAI_TU_CAU_KHIEN = 'tinhthaitucaukhien',
  TINH_THAI_TU_NGHI_VAN = 'tinhthaitunghivan',
  TINH_TU = 'tinhtu',
  TINH_TU_CACH_THUC_MUC_DO = 'tinhtuchicachthucmucdo',
}
